=== MeBouha/greenBin/public/data/greenBin.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <!-- Password restriction -->
    <xs:simpleType name="TypePassword">
        <xs:restriction base="xs:string">
            <xs:minLength value="8"/>
        </xs:restriction>
    </xs:simpleType>

    <!-- Definition des roles -->
    <xs:simpleType name="TypeRole">
        <xs:restriction base="xs:string">
            <xs:enumeration value="admin"/>
            <xs:enumeration value="responsable municipalite"/>
            <xs:enumeration value="responsable service de voirie"/>
            <xs:enumeration value="responsable service d'environnement"/>
            <xs:enumeration value="chef de tournee"/>
            <xs:enumeration value="ouvrier"/>
            <xs:enumeration value="citoyen"/>
        </xs:restriction>
    </xs:simpleType>

    <!-- Type user -->
    <xs:complexType name="TypeUser">
        <xs:sequence>
            <xs:element name="login" type="xs:string"/>
            <xs:element name="password" type="TypePassword"/>
            <xs:element name="nom" type="xs:string"/>
            <xs:element name="prenom" type="xs:string"/>
            <xs:element name="role" type="TypeRole"/>
        </xs:sequence>
        <xs:attribute name="id" type="xs:int" use="required"/>
    </xs:complexType>


    <!-- Liste des utilisateurs -->
    <xs:element name="users">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="user" type="TypeUser" minOccurs="1" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>

        <!-- id unique (clÃ© primaire) -->
        <xs:key name="UserIdKey">
            <xs:selector xpath="user"/>
            <xs:field xpath="@id"/>
        </xs:key>

        <!-- login unique -->
        <xs:unique name="UserLoginUnique">
            <xs:selector xpath="user"/>
            <xs:field xpath="login"/>
        </xs:unique>

    </xs:element>

    <!-- declaration de type de vehicules -->

    <!-- pattern de matricule -->
    <xs:simpleType name="TypeMat">
        <xs:restriction base="xs:string">
            <xs:pattern value="[0-9]{3}TUN[0-9]{4}"/>
        </xs:restriction>
    </xs:simpleType>

    <!-- valeurs possibles de disponibilite -->
    <xs:simpleType name="TypeDispo">
        <xs:restriction base="xs:string">
            <xs:enumeration value="disponible"/>
            <xs:enumeration value="en service"/>
        </xs:restriction>
    </xs:simpleType>

    <!-- element vide chauffeur -->
    <xs:complexType name="TypeChauffeur">
        <xs:attribute name="id"/>
    </xs:complexType>

    <xs:complexType name="TypeVehicule">
        <xs:sequence>
            <xs:element name="matricule" type="TypeMat"/>
            <xs:element name="chauffeur" type="TypeChauffeur"/>
            <xs:element name="disponibilite" type="TypeDispo"/>
        </xs:sequence>
        <xs:attribute name="id" type="xs:string"/>
    </xs:complexType>

    <xs:element name="vehicules">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="vehicule" type="TypeVehicule" minOccurs="1" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
        <xs:key name="VehiculeIdKey">
            <xs:selector xpath="vehicule"/>
            <xs:field xpath="@id"/>
        </xs:key>
        <xs:keyref name="chauffeurRef" refer="UserIdKey">
            <xs:selector xpath="vehicules/vehicule/chauffeur"/>
            <xs:field xpath="@id"/>
        </xs:keyref>
    </xs:element>

    <!-- declaration de type de trashCans -->

    <!-- type coordonnees -->
     <xs:complexType name="TypeCoord">
        <xs:sequence>
            <xs:element name="latitude" type="xs:float"/>
            <xs:element name="longitude" type="xs:float"/>
        </xs:sequence>
     </xs:complexType>

    <!-- type lieu -->
    <xs:complexType name="TypeLieu">
        <xs:sequence>
            <xs:element name="adresse" type="xs:string"/>
            <xs:element name="coordonnees" type="TypeCoord"/>
        </xs:sequence>
    </xs:complexType>
    
    <!-- val de type dechets -->
    <xs:simpleType name="TypeDechets">
        <xs:restriction base="xs:string">
            <xs:enumeration value="plastique"/>
            <xs:enumeration value="verre"/>
            <xs:enumeration value="papier"/>
            <xs:enumeration value="autre"/>
        </xs:restriction>
    </xs:simpleType>

    <!-- val de type status -->
    <xs:simpleType name="TypeStatus">
        <xs:restriction base="xs:string">
            <xs:enumeration value="vide"/>
            <xs:enumeration value="moitie"/>
            <xs:enumeration value="pleine"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:complexType name="TypeTrashCan">
        <xs:sequence>
            <xs:element name="lieu" type="TypeLieu"/>
            <xs:element name="typeDechet" type="TypeDechets"/>
            <xs:element name="status" type="TypeStatus"/>
        </xs:sequence>
        <xs:attribute name="id"/>
    </xs:complexType>

    <xs:element name="trashCans">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="trashCan" type="TypeTrashCan" minOccurs="1" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
        <xs:key name="TrashCanIdKey">
            <xs:selector xpath="trashCan"/>
            <xs:field xpath="@id"/>
        </xs:key>
    </xs:element>

    <!-- declaration de type de tournees -->

    <!-- elements vides (trashCan/ouvrier/vehicule) -->
     <xs:complexType name="TypeTrashCanTournee">
        <xs:attribute name="id"/>
    </xs:complexType>

    <xs:complexType name="TypeOuvrierTournee">
        <xs:attribute name="id"/>
    </xs:complexType>

    <xs:complexType name="TypeVehiculeTournee">
        <xs:attribute name="id"/>
    </xs:complexType>
    <xs:complexType name="TypeTournee">
        <xs:sequence>
            <xs:element name="trashCans">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="trashCan" type="TypeTrashCanTournee" minOccurs="1" maxOccurs="unbounded"/>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
            <xs:element name="ouvriers" minOccurs="1" maxOccurs="1">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="ouvrier" type="TypeOuvrierTournee" minOccurs="1" maxOccurs="unbounded"/>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
            <xs:element name="vehicule" type="TypeVehiculeTournee"/>
            <xs:element name="date" type="xs:date"/>
        </xs:sequence>
        <xs:attribute name="id" type="xs:int"/>
    </xs:complexType>

    <xs:element name="tournees">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="tournee" type="TypeTournee" minOccurs="1" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
        <xs:key name="TourneeIdKey">
            <xs:selector xpath="tournee"/>
            <xs:field xpath="@id"/>
        </xs:key>
        <xs:keyref name="ouvrierRef" refer="UserIdKey">
            <xs:selector xpath="tournees/tournee/emplyees/employee/ouvrier"/>
            <xs:field xpath="@id"/>
        </xs:keyref>
        <xs:keyref name="tashCanRef" refer="TrashCanIdKey">
            <xs:selector xpath="tournees/tournee/trashCans/trashCan"/>
            <xs:field xpath="@id"/>
        </xs:keyref>
    </xs:element>

    <!-- declaration de type de rapports -->

    <xs:complexType name="TypeTourneeRapport">
        <xs:attribute name="id"/>
    </xs:complexType>
    <!-- valeurs de status -->
     <xs:simpleType name="TypeStatusRapport">
        <xs:restriction base="xs:string">
            <xs:enumeration value="present"/>
            <xs:enumeration value="absent"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:complexType name="TypeOuvrierRapport">
        <xs:sequence>
            <xs:element name="nom" type="xs:string"/>
            <xs:element name="prenom" type="xs:string"/>
            <xs:element name="status" type="TypeStatusRapport"/>
        </xs:sequence>
        <xs:attribute name="id" type="xs:int"/>
    </xs:complexType>

    <xs:complexType name="TypeEmployeesRapport">
        <xs:sequence>
            <xs:element name="chefTourne" type="TypeChauffeur"/>
            <xs:element name="ouvriers">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="ouvrier" type="TypeOuvrierRapport" minOccurs="1" maxOccurs="unbounded"/>
                    </xs:sequence>
                    <xs:attribute name="id"/>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="TypeTrashCanRapport">
        <xs:attribute name="id" type="xs:int"/>
        <xs:attribute name="quantite" type="xs:int"/>
    </xs:complexType>
    <xs:complexType name="TypeDechetsCollecteRapport">
        <xs:sequence>
            <xs:element name="trashCan" type="TypeTrashCanRapport" minOccurs="1" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="TypeRapport">
        <xs:sequence>
            <xs:element name="date" type="xs:date"/>
            <xs:element name="tournee" type="TypeTourneeRapport"/>
            <xs:element name="employees" type="TypeEmployeesRapport"/>
            <xs:element name="dechetsCollecte" type="TypeDechetsCollecteRapport" minOccurs="1" maxOccurs="unbounded"/>
        </xs:sequence>
        <xs:attribute name="id" type="xs:int"/>
    </xs:complexType>

    <xs:element name="rapports">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="rapport" type="TypeRapport" minOccurs="1" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
        <xs:key name="RapportIdKey">
            <xs:selector xpath="rapport"/>
            <xs:field xpath="@id"/>
        </xs:key>
        <xs:keyref name="ouvrierRapportRef" refer="UserIdKey">
            <xs:selector xpath="rapports/rapport/employees/ouvriers/ouvrier"/>
            <xs:field xpath="@id"/>
        </xs:keyref>
        <xs:keyref name="chefTourneeRapportRef" refer="UserIdKey">
            <xs:selector xpath="rapports/rapport/employees/chefTournee"/>
            <xs:field xpath="@id"/>
        </xs:keyref>
        <xs:keyref name="trashCanRapportRef" refer="TrashCanIdKey">
            <xs:selector xpath="rapports/rapport/dechetsCollecte/trashCan"/>
            <xs:field xpath="@id"/>
        </xs:keyref>
    </xs:element>

    <!-- declaration de type de travails -->
    <xs:simpleType name="TypeEtatTravail">
        <xs:restriction base="xs:string">
            <xs:enumeration value="complet"/>
            <xs:enumeration value="en cours"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:complexType name="TypeTravail">
        <xs:sequence>
            <xs:element name="date" type="xs:date"/>
            <xs:element name="lieu" type="xs:string"/>
            <xs:element name="etat" type="TypeEtatTravail"/>
        </xs:sequence>
        <xs:attribute name="id" type="xs:int"/>
    </xs:complexType>

    <xs:element name="travaux">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="travail" type="TypeTravail"/>
            </xs:sequence>
        </xs:complexType>

        <xs:key name="TravailIdKey">
            <xs:selector xpath="travail"/>
            <xs:field xpath="@id"/>
        </xs:key>
    </xs:element>

    <!-- declaration de type de notifications -->
    <!-- elements vides: chef tournee/travail -->
    <xs:complexType name="TypeChefTourneeNotif">
        <xs:attribute name="id" type="xs:int"/>
    </xs:complexType>
    <xs:complexType name="TypeTravilNotif">
        <xs:attribute name="id" type="xs:int"/>
    </xs:complexType>
    <xs:complexType name="TypeNotif">
        <xs:sequence>
            <xs:element name="chefTournee" type="TypeChefTourneeNotif"/>
            <xs:element name="travail" type="TypeTravilNotif"/>
            <xs:element name="contenu" type="xs:string"/>
        </xs:sequence>
        <xs:attribute name="id" type="xs:int"/>
    </xs:complexType>

    <xs:element name="notifications">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="notification" type="TypeNotif" minOccurs="0" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
        <xs:unique name="uniqueNotifId">
            <xs:selector xpath="notifications/notification"/>
            <xs:field xpath="@id"/>
        </xs:unique>
    </xs:element>

    <!-- declaration de type de reclamations -->
    <!-- elements vides: citoyen -->
    <xs:complexType name="TypeCitoyenRec">
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute name="id" type="xs:int" use="required"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>

    <xs:complexType name="TypeReclamation">
        <xs:sequence>
            <xs:element name="citoyen" type="TypeCitoyenRec"/>
            <xs:element name="contenu" type="xs:string"/>
            <xs:element name="date" type="xs:date"/>
            <xs:element name="status" type="StatusType"/>
            <xs:element name="type" type="TypeReclamationType"/>
        </xs:sequence>
        <xs:attribute name="id" type="xs:int" use="required"/>
    </xs:complexType>

    <xs:simpleType name="StatusType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="new"/>
            <xs:enumeration value="in-progress"/>
            <xs:enumeration value="resolved"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="TypeReclamationType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="Collecte"/>
            <xs:enumeration value="Dommage"/>
            <xs:enumeration value="Horaire"/>
            <xs:enumeration value="Sanitaire"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:element name="reclamations">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="reclamation" type="TypeReclamation" minOccurs="0" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
        <xs:key name="ReclamationIdKey">
            <xs:selector xpath="reclamation"/>
            <xs:field xpath="@id"/>
        </xs:key>
    </xs:element>

</xs:schema>

=== MeBouha/greenBin/public/data/tournee.xml
<?xml version="1.0" encoding="UTF-8"?>
<tournees xmlns:xs="http://www.w3.org/2001/XMLSchema-instance"
           xs:noNamespaceSchemaLocation="greenBin.xsd">
    <tournee id="1"> <!-- id: key -->
        <trashCans>
            <trashCan id="1"/>
            <trashCan id="2"/>
        </trashCans>
        <!--<employees>-->
            <!--  <chefTourne id="1"/> deja mawjoud fl vehicule-->
            <ouvriers>
                <ouvrier id="2"/>
                <ouvrier id="3"/>
            </ouvriers>
        <!--</employees>-->
        <vehicule id="1"/>
        <date>2024-06-15</date>
    </tournee>
</tournees>

=== MeBouha/greenBin/public/data/reclamation.xml
<?xml version="1.0" encoding="UTF-8"?>
<reclamations xmlns:xs="http://www.w3.org/2001/XMLSchema-instance" xs:noNamespaceSchemaLocation="greenBin.xsd">
  <reclamation id="5">
    <citoyen id="5">Michel Dubois</citoyen>
    <contenu>Odeur naus√©abonde provenant du point de collecte du quartier</contenu>
    <date>2024-01-11</date>
    <status>resolved</status>
    <type>Sanitaire</type>
  </reclamation>
  <reclamation id="6">
    <citoyen id="6">prenom nom</citoyen>
    <contenu>content</contenu>
    <date>2025-12-06</date>
    <status>resolved</status>
    <type>Sanitaire</type>
  </reclamation>
  <reclamation id="9">
    <citoyen id="9">mohamed</citoyen>
    <contenu>zebla taycha</contenu>
    <date>2025-12-12</date>
    <status>new</status>
    <type>Collecte</type>
  </reclamation>
  <reclamation id="10">
    <citoyen id="10">bouhamed</citoyen>
    <contenu>zeblaa brchaa</contenu>
    <date>2025-12-12</date>
    <status>new</status>
    <type>Collecte</type>
  </reclamation>
  <reclamation id="11">
    <citoyen id="11">daouad</citoyen>
    <contenu>zbla zbla</contenu>
    <date>2025-12-12</date>
    <status>new</status>
    <type>Collecte</type>
  </reclamation>
</reclamations>

=== MeBouha/greenBin/public/travaux.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<travaux xmlns:xs="http://www.w3.org/2001/XMLSchema-instance" xs:noNamespaceSchemaLocation="greenBin.xsd">
  <travail id="2">
    <date>2025-12-10</date>
    <lieu>Route el Ain klm1</lieu>
    <cords>
      <latitude>34.740</latitude>
      <longitude>5.2</longitude>
    </cords>
    <etat>complet</etat>
  </travail>
</travaux>

=== MeBouha/greenBin/public/data/rapport.xml
<?xml version="1.0" encoding="UTF-8"?>
<rapports xmlns:xs="http://www.w3.org/2001/XMLSchema-instance" xs:noNamespaceSchemaLocation="greenBin.xsd">
  <rapport id="1">
    <date>2024-06-10</date>
    <tournee id="1"></tournee>
    <employees>
      <chefTourne id="1"></chefTourne>
      <ouvriers>
        <ouvrier id="3">
          <nom>Smith</nom>
          <prenom>Jane</prenom>
          <status>present</status>
        </ouvrier>
      </ouvriers>
    </employees>
    <dechetsCollecte>
      <trashCan id="1" quantite="50"></trashCan>
      <trashCan id="2" quantite="30"></trashCan>
    </dechetsCollecte>
    <kilometrage>120</kilometrage>
    <co2Emis>25.5</co2Emis>
    <carburantConsomme>15.2</carburantConsomme>
  </rapport>
  <rapport id="2">
    <date>2025-11-29</date>
    <tournee id="1"></tournee>
    <employees>
      <chefTourne></chefTourne>
      <ouvriers>
        <ouvrier id="2">
          <nom>nomCT</nom>
          <prenom>prenomCT</prenom>
          <status>present</status>
        </ouvrier>
        <ouvrier id="3">
          <nom>user</nom>
          <prenom>lastname</prenom>
          <status>absent</status>
        </ouvrier>
      </ouvriers>
    </employees>
    <dechetsCollecte>
      <trashCan id="1" quantite="5"></trashCan>
    </dechetsCollecte>
    <kilometrage>85</kilometrage>
    <co2Emis>18.3</co2Emis>
    <carburantConsomme>10.7</carburantConsomme>
  </rapport>
  <rapport id="4">
    <date>2026-12-25</date>
    <tournee id="2"></tournee>
    <employees>
      <chefTourne id="2"></chefTourne>
      <ouvriers>
        <ouvrier id="1">
          <nom>-</nom>
          <prenom>user2</prenom>
          <status>present</status>
        </ouvrier>
        <ouvrier id="101">
          <nom>-</nom>
          <prenom>user</prenom>
          <status>absent</status>
        </ouvrier>
      </ouvriers>
    </employees>
    <dechetsCollecte>
      <trashCan id="5" quantite="7"></trashCan>
    </dechetsCollecte>
    <kilometrage>2.23</kilometrage>
    <co2Emis>3.12</co2Emis>
    <carburantConsomme>66.9</carburantConsomme>
  </rapport>
  <rapport id="5">
    <date>2025-12-25</date>
    <tournee id="1"></tournee>
    <employees>
      <chefTourne id="2"></chefTourne>
      <ouvriers>
        <ouvrier id="1">
          <nom>-</nom>
          <prenom>user2</prenom>
          <status>present</status>
        </ouvrier>
        <ouvrier id="101">
          <nom>-</nom>
          <prenom>user</prenom>
          <status>absent</status>
        </ouvrier>
      </ouvriers>
    </employees>
    <dechetsCollecte>
      <trashCan id="4" quantite="50"></trashCan>
    </dechetsCollecte>
    <kilometrage>1.39</kilometrage>
    <co2Emis>1.95</co2Emis>
    <carburantConsomme>41.7</carburantConsomme>
  </rapport>

    <rapport id="6">
        <date>2025-12-12</date>
        <tournee id="1"/>
        <employees>
            <chefTourne id="2"/>
            <ouvriers>
                <ouvrier id="101">
                    <nom>-</nom>
                    <prenom>ouvrier2</prenom>
                    <status>absent</status>
                </ouvrier>
            </ouvriers>
        </employees>
        <dechetsCollecte>
            
        </dechetsCollecte>
        <kilometrage>0.65</kilometrage>
        <co2Emis>0.91</co2Emis>
        <carburantConsomme>19.50</carburantConsomme>
    </rapport>
</rapports>
